### ISSUE TITLE
Invalid scope using default integration client_id/secret

### ISSUE THREAD

**Issue by dstaudt** [CiscoDevNet/webex-integration-sample#3]
Testing the web app using the default client_id/secret, after clicking on the 'Start Oauth Flow' button, an error is displayed mentioning 'invalid scope'.  Is it possible the default integration does not have the 'spark:people_read' scope enabled?

Note, if 'spark:all' is enabled (and nothing else), this will not actually match when requesting 'spark:people_read' - all specific scopes requested ('spark:all' and 'spark:people_read') would need to be checked in the integration settings.

**Comment by ObjectIsAdvantag** [comment]
Yeh, that was it David, the spark:people_read was not checked.
Just re-checked it, and that fixes it.
Thanks for pointing this.

![image](https://user-images.githubusercontent.com/49432/37827693-cd70d284-2e98-11e8-8af7-82b8e92bf4b0.png)

**Comment by ObjectIsAdvantag** [comment]
Note: the Spark4Devs UI does not let you check both spark:all and spark:people_read scopes. 
I have a ticket opened at devsupport about that topic ;-)
